### ISSUE TITLE
User Auth MVP Review

### ISSUE THREAD

**Issue by aimyaa** [aimyaa/PacaCamp#2]

**Comment by vawhitehouse** [comment]
It's looking good! Here are a few things to add: 

- [ ] If possible, try to find a more similar font for the top left logo and use all caps.

- [ ] It looks like HipCamp uses modals for their session forms so we should work on doing that also. 

- [ ] "Have an account? Sign In" on sign up form - the "Sign up should have a heavier font weight and should only be underlined on hover.

- [ ] The login and sign up buttons should mimic the animation on HipCamp. 

- [ ] Have the alpaca icon in the navbar be a bit smaller and center align the "Trips" link next to it. 

- [ ] The font-size for PacaCamp looks larger than HipCamp and the NavBar links look like they may be slightly larger than Hipcamp.

Nice job on the logout dropdown! The animation on hover looks great!

**Comment by david-dickinson** [comment]
Two last small features:
- [ ] Style errors in the boxed format that HipCamp uses for failed logins
- [ ] Set your log out button's width such that it runs the hover animation wherever you hover over the entry in the dropdown, not only when you hover over the text

Feel free to check these features off as you resolve them. Nice work!

**Comment by vawhitehouse** [comment]
One last thing:

- [ ] Be sure that all error messages match HipCamp ("Invalid email or password." rather than "Invalid login credentials. Please try again.")

Great work!!
