### ISSUE TITLE
Spots MVP Review

### ISSUE THREAD

**Issue by aimyaa** [aimyaa/PacaCamp#3]

**Comment by vawhitehouse** [comment]
Spots are looking good! Here are few notes:

Spot show:

- [ ] Activity boxes should be smaller and text should be below box. 
- [ ] Lodging provided, essentials, etc, sections - list items that are available should be a darker color than the those that are unavailable.
- [ ] Also, these sections should be able to fit 3 across the page. 
- [ ] Details  sections - make sure font weights all match HipCamp.
